### ISSUE TITLE
Date/time does not appear for forum posts

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1015]

**Comment by paulolc** [comment]
Some observations so far, by looking only at the source code in the browser, regarding this issue:
-  The tag where the date should appear on the "topics" and "posts" views is empty and have the attribute title with "Invalid Date":
`<span class="timeago" title="Invalid Date"></span>`
- The forum homepage the dates are ok. They do not appear because the date permalink has class "visible-xs pull-right". If you change it to "hidden-xs" the date appears
- The dates on the rss feeds of all views seem to also be ok

<speculation>Maybe some conversion problem goin on?</speculation>

**Comment by Wardormeur** [comment]
It could be a difference between the nodebb version and the version of the theme.
If somebody wants to have a look, it's in https://github.com/CoderDojo/nodebb-theme-cd-persona, which is a fork of https://github.com/NodeBB/nodebb-theme-persona

**Comment by paulolc** [comment]
Yes, @Wardormeur. It looks to me that you are right. 

Maybe the date field used in the views templates should be **timestampISO** and not **relativeTime**.

In the views templates that have the issue, the date field being used is **relativeTime**, but in the view where the date is OK, the field is **timestampISO** instead. Furthermore, a search for **relativeTime** on the NodeBB source code comes up empty. If you search for **timestampISO** though, there are quite a few results. 

To recap:

1. Forum homepage (categories list) is almost **OK**   (date is ok but does not appear, maybe it's intentional on this page)
2. Topics list is **NOT OK** - ("Invalid Date")
3. Posts list is **NOT OK** - ("Invalid Date")

and looking at the views templates, the fields are:

1. **OK** - Forum homepage view (**templates/partials/categories/item.tpl**)
```html
<small class="timeago" title="{../teaser.timestampISO}"></small>
```
2. **NOT OK** - Topics list view (**templates/partials/topics_list.tpl**)
```html
<span class="timeago" title="{topics.relativeTime}"></span>
```
3. **NOT OK** - Posts list view (**templates/partials/posts_list.tpl**)
```html
<span class="timeago" title="{posts.relativeTime}"></span>
```

Cheers
.Paulo LC

**Comment by butlerx** [comment]
this is fixed and live now
