### ISSUE TITLE
Add WYSIWYG editor for event description

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1028]
Event description already allows you to input HTML tags for formatting, so we should use ckeditor for WYSIWYG like we do elsewhere for fields like this.

**Comment by gaursagar** [comment]
Can I please get more details about the issue? I would love to help.

**Comment by Wardormeur** [comment]
Sure :)
First setup your env based on cp-local (https://github.com/CoderDojo/cp-local-development)
Look into web/public/js/directives/event/cd-create-event/template.dust in cp-zen-platform (https://github.com/CoderDojo/cp-zen-platform) and replace the editor.
Afterwards, you'll probably have to look into the directives that display the text (eg: web/public/js/directives/event/detail) and see if the binding requires a change now that's it's HTML based instead of pure text
HFGL !

**Comment by andarilhoz** [comment]
Sooo, i could grab this one, dont know if @gaursagar  already did something, but if i could do it, please let me know (:

**Comment by ilyabiryukov-r7** [comment]
I'll take this one

**Comment by howardjing** [comment]
I'm assuming this issue was never done -- I can take a stab at this today.

**Comment by Wardormeur** [comment]
Cool !
Jump on gitter if you need help :)
https://gitter.im/CoderDojo/community-platform

**Comment by howardjing** [comment]
As far as I can tell, this has been completed.

On the event page:
![image](https://cloud.githubusercontent.com/assets/831651/26013202/567854ec-3725-11e7-8060-e875cdcf432f.png)

The editor itself:
![image](https://cloud.githubusercontent.com/assets/831651/26013236/73b74770-3725-11e7-8214-9dd59745e6af.png)

Is there any further work necessary here?

**Comment by Wardormeur** [comment]
Yeah, i guess the front-end need a bit of work in order to accept anything. example : 
![selection_074](https://cloud.githubusercontent.com/assets/1755357/26015037/13be79b0-3757-11e7-94c5-767090eee1b9.png)
My unicorn is a bit running away, allright :p 
At the same time, it's allright-ish on the booking page because it doesn't contain much logic, quite "CRUD".
![selection_075](https://cloud.githubusercontent.com/assets/1755357/26015071/3dbceb52-3757-11e7-9acd-40c2174c73f8.png)

My recommendation would be to look into limiting the description of an event for the dojo page in order to avoid an overflow like this unicorn madness :p

**Comment by howardjing** [comment]
I added some basic html sanitization to the saveEvent function here: https://github.com/CoderDojo/cp-events-service/pull/138/files
