### ISSUE TITLE
Create keys for .po file

### ISSUE THREAD

**Issue by Wardormeur** [CoderDojo/community-platform#1060]
For a better dev process for translations, we need to replace strings for translation by keys.
Considering po file doesn't support keys as it, we need to complete them with a translation file mapping po file "keys" (which are the english string) to a development "key" (eg error.general)
This implies replacing in the front-end all the strings by the corresponding key

**Comment by niccokunzmann** [comment]
There were keys, as I remember, in the crodwin platform. It was not
known by me what they mean.
There was this "error.general" or something alike. This can not be used
a a translation text. Some people translated it, some did not.

My request: When you replace the sentences by keys, please make sure
that crowdin shows the sentences in English and not the keys.


Am 06.10.2016 um 12:35 schrieb Wardormeur:

**Comment by DanielBrierton** [comment]
Hey Nicco,

Don't worry, nothing will actually change in CrowdIn. We're simply adding a file to the repo that maps variable names to strings so we can reference to a single string, rather than duplicating it across files. With the PO file format, the msgid is supposed to be the untranslated string, and we will be keeping it that way, so it will display that way in CrowdIn. The likes of `error.general` shouldn't really exist in CrowdIn. It should be the actual error message.

**Comment by Wardormeur** [comment]
@DanielBrierton I believe this has not been adopted in cp-zen-frontend. If we're not pushing for it internally, we should close this ticket.
So. should we? :)

**Comment by DanielBrierton** [comment]
Yeah, we've ended up not doing this... So yeah, close.
