### ISSUE TITLE
Complete SPF/DKIM configuration for emails

### ISSUE THREAD

**Issue by Wardormeur** [CoderDojo/community-platform#1113]
~~We have a bunch of emails which drops because of lack of authentication on our emails through Sendgrid.
Adding those headers should help.~~
As stated by @BenChapman , the issue is not SPF by itself which is added by sendgrid, but the whitelabeling

- [ x] SPF whitelabeling
- [x] email link whitelabeling

**Comment by BenChapman** [comment]
The emails you send out via SendGrid already have the correct SPF and DKIM signatures, they're attached automatically by SendGrid. Reason for this is that SendGrid uses a sendgrid.com address in the `MAIL FROM` command and this will pass most email provider filters since it's valid. It may not pass on some exceptionally restrictive providers. I think to overcome that you need to use [whitelabeling](https://sendgrid.com/docs/User_Guide/Settings/Whitelabel/index.html).

<img width="1172" alt="screen shot 2017-03-18 at 18 42 00" src="https://cloud.githubusercontent.com/assets/479354/24074977/0f083004-0c0b-11e7-8812-e6bafa23fb52.png">

**Comment by Wardormeur** [comment]
Thanks @BenChapman for the investigation :+1:

**Comment by Wardormeur** [comment]
Whitelabeling done
![selection_047](https://cloud.githubusercontent.com/assets/1755357/24143766/a64135f6-0e22-11e7-8293-3c47db1ec61f.png)

**Comment by Wardormeur** [comment]
Updated first comment to reflect real issue/actions

**Comment by Wardormeur** [comment]
email link whitelisting done
