### ISSUE TITLE
Remove View More button

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#1117]
We have a very [long Dojo page](http://coderdojopotsdam.github.io/). Problems arise with the view more button:

- People usually do not see the view more button.
- Everyone has to click it to get to the content.

In order to remove the view-more button, we should first identify what problems it solved and then find another solution to the problems.

What problems did the view-more button solve?

**Comment by Wardormeur** [comment]
"View More" was because the Dojo description is a free text area for any additional info.
Having it too long will simply push back every other info, such as Events and map way too far (scrolling).
Restricting the number of words from the textarea is a bad idea considering different languages "length" and the whole purpose of the field itself (extra info which is not "shared" with others dojos setup).
The "View more" action could be triggered by hover, but that may be "disturbing" in term of UI.
The other thing i'm thinking of is to find a way to make it more visible (higher contrast/background color)?

**Comment by Wardormeur** [comment]
The Dojo page has been reworked last year :s 
The description is now at the end of the page, but not "reduced" anymore
