### ISSUE TITLE
Re-add private banner to Dojo listing & remove lock symbol

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#1153]
For private Dojos a banner under the name of the Dojo (see terrible sketch for placement idea) should be added - the lock symbol should be removed as this is not prominent enough. 

Text would be;

'Private Dojos are by invite only or for specific people who are members of an organisation or school. The general public should not contact to attend this Dojo.'

cc'ing @Giustina to confirm wording after review.

**Comment by Wardormeur** [comment]
A lock may not be the best icon ui-wise, but banners are literally a bad idea. To be included for review by an ui-designer instead?

**Comment by rosalanghammer** [comment]
Agree. It needs to be something more obvious than the lock right now. 

This was my terrible sketch which I forgot to attach. 

![screen shot 2017-02-21 at 15 20 54](https://cloud.githubusercontent.com/assets/12827424/23213620/9c2789b6-f8d9-11e6-94a7-220268dc0a16.png)

**Comment by BenChapman** [comment]
A badge may be a good way to go. If looking for a Dojo for the first time, one of the key pieces of information for a user is "Can I go here?". A badge is obvious but reasonably unobtrusive way of communicating this.

<img width="1384" alt="screen shot 2017-03-18 at 19 07 00" src="https://cloud.githubusercontent.com/assets/479354/24075242/635c69a0-0c0f-11e7-9997-d64d2359d53b.png">

----

**Sidenote**

The tabs at the top right are a little confusing. There's a discontinuity between those and the "Status" badges in the image mid-left, since they seem to be all "status" related. Some small changes might help reduce the clutter a little:

* Instead of we need mentors, have an application form if they need mentors, or just have it put in the notes section.
* Instead of the "In Planning" status, say in the booking section that tickets aren't available yet but will be in the future. Answers the question "Can I go now?".
* Since unverified Dojos are no longer accessible, why bother with the verified symbol at all? If anything it causes confusion between verified and Tao.

**Comment by DanielBrierton** [comment]
We need to consider how we display what Private actually means to users (like how they get in if it's a Dojo in their school), but without it looking ugly. If we could get a UI designer to look at this, it would be optimal. Otherwise, I might take a whack at it at some point.

> Since unverified Dojos are no longer accessible, why bother with the verified symbol at all?
Good point.

**Comment by BenChapman** [comment]
Just to give a bit of older context on why it never had any info on how to join. The reason they were originally added is to recognise them as Dojos.

here was originally an assumption that private Dojos would be able to communicate internally (they were mostly in schools) and organise how to sign up. This is why they were just marked private before Zen got redone. It might be useful to validate if private Dojos actually need anything more than already exists with existing notes section, like with regular Dojos.

**Comment by Wardormeur** [comment]
Closing off, a wall of text has been added to explain the private aspect of a dojo
![selection_170](https://user-images.githubusercontent.com/1755357/31015333-77849aaa-a517-11e7-9180-ea5ec04ba49e.png)
