### ISSUE TITLE
As a volunteer, if I register as a volunteer set my user role to volunteer

### ISSUE THREAD

**Issue by conoramurphy-zz** [CoderDojo/community-platform#1245]
This is only the start of this ticket.

**Business Goal**
The point here is that if someone signs up as a volunteer we should know. This is because as people start to try to take actions on a pipeline of volunteers we need to know not only when a volunteer finds a club but also when they do not. This is so co-ordinators and others can action and reach out to them.

There are a few possible variations of this.

**Task Possibilities**
 - Just have a URL modifier ?user=volunteer so that we can link from volunteer pages and webinars etc.
 - Redo the registration form using the event booking page.
 - Another option?

**Comment by Wardormeur** [comment]
We went full loop here.
We already had that before, and the problem was parents were registering as whatever they would (sometimes "champion", sometimes "volunteer", and eventually "parent"). That doesn't solve the problem of a user being a mentor in a Dojo, and a champion in another.
Even if we set a flag to know that the user wants to be a volunteer, what's the goal behind? What are we doing with it?
My proposal here is rather to go through this loop-hole of "registering as a volunteer" would be to offer in the dashboard, post-registration, a potential flow to "volunteer at a Dojo". That's assuming that the user goes through registration first, which is I assume, what we're talking about here.

**Comment by conoramurphy-zz** [comment]
Updated description. I think it might make sense to go through the volunteer flows in detail with the team (Monday?). We have needs to basically standardise what we collect and this is a step in building fully coherent volunteer flows down the line.

**Comment by Wardormeur** [comment]
Is this still valid ?

**Comment by conoramurphy-zz** [comment]
Nah close it. It might re-rise in a new form down the line but close this.
