### ISSUE TITLE
Waiting list feature fails on a full event

### ISSUE THREAD

**Issue by grega** [CoderDojo/community-platform#1273]
A full event doesn't allow a waiting list to be created.

It would see that a new ticket type for the waiting list needs to be added, but the event form won't allow any ticket options to be selected:

![Screenshot 2019-09-03 at 12 16 19](https://user-images.githubusercontent.com/91799/64170045-03026800-ce47-11e9-816d-6359f0fc1dd4.png)

This is old, but wondering if there's a link at all: https://github.com/CoderDojo/community-platform/issues/1068

**Comment by grega** [comment]
Ref: https://forums.coderdojo.com/topic/663/waitlist-functionality-changed

**Comment by Wardormeur** [comment]
As far as I'm aware, we never came to implement a waitlist. The "alternative" we had was allowing for tickets to be "accepted" by the Event Manager. If they are accepted, they are counted towards the total, if they're not (and hence "pending") they don't. This behavior is defined by the field "TicketApproval" on the event itself.
(https://github.com/CoderDojo/events-service/commit/7548e3109f551060d5d4c0d6d9a1f577929bec8e#diff-b3c5b2e2eae7203c9c01350743845a6eR13)
So the issue here could be : 
 - we blocked booking tickets even when not all tickets have been approved
 - or the event is misconfigured

**Comment by conoramurphy-zz** [comment]
Yes. This is an incorrect direction of ire here. The new create event form does not allow for ticket approval. Some people were using that as a hack for a pseudo waitlist. This is not allowed any more. Combine this with the fact that there is poor messaging around booked out events has led to this confusion.

Closing this issue as this is not adressing a current bug. Adding https://github.com/CoderDojo/community-platform/issues/1274 as a placeholder for future improvements to the booking clarity based off the new simplified events structure.
