### ISSUE TITLE
Delete waitlist language from zen

### ISSUE THREAD

**Issue by conoramurphy-zz** [CoderDojo/community-platform#1278]
There is various reference to waitlist in zen. There is no waitlist functionality. So we should remove that language.

After Guillaumes feedback I've update this ticket to

**Task**
Change all references from `Waitlist` to `Awaiting approval`

**Comment by Wardormeur** [comment]
Only references found are https://github.com/CoderDojo/cp-zen-platform/search?q=waitlist&unscoped_q=waitlist and https://github.com/CoderDojo/cp-zen-platform/search?q=waiting&unscoped_q=waiting
Those are the event management page post publication; or applications management page if we want to call it that.
While I agree it should be removed, I would also recommend looking at reworking that page (there was a PoC lying around to simplify the sessions and migrate to the new frontend (https://github.com/CoderDojo/cp-zen-frontend/pull/109)) as this belongs to the old frontend.

Edit: as a matter of fact, there is a "waiting list", that's the awaiting approval list of applications. Now, it doesn't behave the way people expect it to be (an unlimited list of applications), but rather as a filter for prioritisation which is manual (rather than time based like a waiting list would be). My proposal would be to rename "Waiting list" to "applications awaiting approval".
