### ISSUE TITLE
Not enough Spacing in between lines in some sections in the profile

### ISSUE THREAD

**Issue by kennanseno** [CoderDojo/community-platform#522]
the second line seems to overlap the bottom part of the first line on badge and dojo section in a profile.Can we add a bit more spacing in between lines.

Profile: http://zentest.coderdojo.com/dashboard/profile/59bedf7e-e1d6-4bda-b595-1ba7e5a96f79
Badge section:
<img width="854" alt="screen shot 2015-08-26 at 15 38 33" src="https://cloud.githubusercontent.com/assets/7852866/9497235/f977b3b0-4c0b-11e5-8880-31a9bc9d1c1e.png">

Dojo section:
<img width="967" alt="screen shot 2015-08-26 at 15 35 53" src="https://cloud.githubusercontent.com/assets/7852866/9497244/051e11b4-4c0c-11e5-9749-0a2bf626e5ca.png">

**Comment by tangentfairy** [comment]
__Technical spec__
CSS is here https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/css/dashboard.less
Template is here https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/templates/dojos/user-profile.dust#L114

I'd suggest using a truncate class and giving this a fixed height so it shows max there lines. Also reduce the font size so that long Dojo names will show.

**Comment by DanielBrierton** [comment]
This is no longer an issue, closing.
