### ISSUE TITLE
All applicants not showing on check in list

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#616]
Check event id c8175eca-2224-4a6a-b663-0f09fc87d302

There are three applicants listed to check in, but in the database there are more. There are 11 approved people attending the event so some are missing.

**Comment by daveymoran-nearform** [comment]
fixed - have removed the event date search criteria.

will update issue labels when ready for testing.

**Comment by daveymoran-nearform** [comment]
have to roll back on this update as the event date is actually needed to identify individual attendances in a recurring event.
because the event time can be altered at any time we have no way (in the current pg schema) to identify attendants for recurring events outside of using the event date, which means we will have inconsistent data whenever an event time is changed.

**interim** solution: i will disable the editing of event times after the initial save until the new event system that @david-cahill is working on

**Comment by daveymoran-nearform** [comment]
fixed. the appropriate records in the attendance table will be updated whenever an event start date is changed.
will update issue labels when this is ready for testing.
