### ISSUE TITLE
Include text explaining you need to register in invite emails

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#676]
Parents are confused when they receive an invite to a Dojo. They don't understand that they need to register an account on the system.

Include the following text in all invite emails: "In order to accept this invite, you will need to register for an account on Zen."

**Comment by tangentfairy** [comment]
Added request for comments in case a community member has an idea on how we can make this clearer.

**Comment by Aryess** [comment]
Yes! I was about to write the same ticket. Got my invite for Docklands, and spend a good 5 minutes wondering while it wouldn't take my login and password.

I would suggest either adding your text in the email, or change the invite endpoint. If the user is logged in, add the account as it works now, if now, redirect to the registration page instead of login. Maybe with a flash "You need to create an account first" or something better worded.

**Comment by tangentfairy** [comment]
Adding to the email now is the quickest thing, so added the "suitable for beginners" label. 

I think we could detect on the login page if this is an invite link, and we show a banner saying "Please login or create an account to accept this invitation"

**Comment by tangentfairy** [comment]
__Technical spec__
See here for template https://github.com/CoderDojo/cp-users-service/tree/master/email-templates
We're using mailtrap.io for catching mails, contact me for the login.
