### ISSUE TITLE
United Kingdom split into two countries in list

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#692]
Can we just have one section - "United Kingdom"?

![screen shot 2015-09-24 at 10 59 56](https://cloud.githubusercontent.com/assets/1136491/10070605/802e0d18-62ab-11e5-9794-45beb723795d.png)

**Comment by BenChapman** [comment]
This seems to be a database/import issue. The country_name field is getting set to "United Kingdom" for new Dojos, but Dojos imported from Zen got the name "United Kingdom of Great Britain & Northern Ireland".

**Comment by tangentfairy** [comment]
Sounds like we could just update the db so that they are all "United Kingdom" then! Sound good?

**Comment by BenChapman** [comment]
Yes, but this issue may also exist for other countries with two forms of name (e.g. Mexico or Belgium). Once it's done for each of them that should be it, easiest might be to change them based on the alpha2 code since that is consistent. Country names used in the platform are here: https://zen.coderdojo.com/api/1.0/countries

**Comment by tangentfairy** [comment]
Sounds good, I will take a look at doing this.

**Comment by tangentfairy** [comment]
All the countries are fixed now!
