### ISSUE TITLE
Allow champions to invite mentors

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#775]
RTP Dojo Champion, and Founder, (https://zen.coderdojo.com/dashboard/dojo/us/rtp/rtp-1) is unable to invite mentors to join nor can they accept join requests.

See two errors;
![kata-error-mentor-join2015-10-28_15-46-52](https://cloud.githubusercontent.com/assets/12827424/10824716/71121742-7e59-11e5-8a3d-e455b6ae4a93.jpg)
![kata-invite-no-mentor2015-10-29_10-26-42](https://cloud.githubusercontent.com/assets/12827424/10824717/7236aca0-7e59-11e5-9990-6a91c7a68796.jpg)

Update: We need to allow champions to invite mentors.

**Comment by tangentfairy** [comment]
Need to confirm that the user was definitely logged in as the correct account when trying to accept the request.

**Comment by rosalanghammer** [comment]
Logged in as user and errors still occurring. 

User has been logged in as correct account when trying to accept account and only users available to invite are Parent/Guardian, Ninja Over 13 and Ninja Under 13 as in screenshot above.

**Comment by tangentfairy** [comment]
The issue was that she didn't have the "mentor" user type on her account. Non mentors cannot invite mentors at the moment.

I think this is a little confusing though as she was also a champion. So I'll update this issue to turn it into an improvement: we need to make it so that champions are allowed to invite mentors also.

**Comment by rosalanghammer** [comment]
We need to also allow Champions to add 'Champions'.

**Comment by Wardormeur** [comment]
Deployed !
