### ISSUE TITLE
End to end API tests

### ISSUE THREAD

**Issue by dberesford** [CoderDojo/community-platform#80]
Need a very small suite of smoke tests for the UI. This will also feed into #61 as well as acting as a testsuite for #38

**Comment by Wardormeur** [comment]
Done so far : 

- [ ] Profile visibility
- [ ] Registration
- [ ] Login
- [ ] Event (C -RUD)
- [ ] Registration

cc @DanielBrierton let's maintain this if possible :)

**Comment by Wardormeur** [comment]
The e2e-test repo has been deprecated, mainly because the UI is being rewritten.
We now tests the front-end through a mock server, making it easier to develop on and easier to test (no need to deploy the whole fleet of microservices).
Closing off as this is now part of the normal development flow (also know as "it's finished" :) )
