### ISSUE TITLE
'Officially Verified' text in dojo detail adding extra line

### ISSUE THREAD

**Issue by kennanseno** [CoderDojo/community-platform#872]
Officially Verified adds an extra line in there. I think 'Verified' text would suffice.

![before](https://cloud.githubusercontent.com/assets/7852866/12216225/aec9387a-b6d2-11e5-8d42-9c51018b2c42.JPG)

after change:
![after](https://cloud.githubusercontent.com/assets/7852866/12216229/bca799fa-b6d2-11e5-8f19-4c5954d9fb8a.JPG)

**Comment by tangentfairy** [comment]
Up to @rosalanghammer if she thinks it would be okay to change this.

One reason not to do this would be because users may not know what "Verified" means. Suggest we add a tooltip (title attribute in html) to explain what verified means, when the user hovers over the tick mark and verified. 

We will inevitably have a Dojo with an even longer name at some stage that will push "verified" to the next line in the future anyway.

**Comment by kennanseno** [comment]
yea, it only happens on certain length dojo names, it's fine since they all get bumped down anyways.

<img width="717" alt="screen shot 2016-01-09 at 17 46 22" src="https://cloud.githubusercontent.com/assets/7852866/12217457/fe56fa46-b6f8-11e5-8d43-deaffbd0d2e2.png">

**Comment by rosalanghammer** [comment]
I would just go for 'Verified' - hopefully due to this mechanism being used on twitter etc. this is recognisable to users. Also no unverified Dojos should be viewable anyway!

**Comment by tangentfairy** [comment]
Cool, you can change it then if you want @kennanseno
