### ISSUE TITLE
Register>UserType>Infobox too big and missing formatting

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#996]
![capture](https://cloud.githubusercontent.com/assets/564768/17082573/09b21b5c-5184-11e6-9f1a-91c6f67389ba.PNG)
- [ ] The size is so big it does not fit on the screen
- [ ] Bullet points are not shown as such and miss the bullet
  - Champion
  - Ninja
  - ...
- [ ] Bullet points should be ordered so that they have the most impact
  1. Ninja - They do not read so much
  2. Mentor - I do not know about the rest but this would be my suggestion
  3. Parent
  4. Champion
## Solutions
- A solution could be to reformat the box.
- Another solution uses the free space on the right below the Log-In and the info box redirects to it.

**Comment by Wardormeur** [comment]
Thanks for the report !
We'll be starting a cleaning spring sprint starting next week (https://github.com/CoderDojo/community-platform/issues/962), and a couple of rethinking of the codebase. One of the decision made was to simplify the registration usertype as it was bringing too many errors(codebase wise)/misunderstanding ( user wise). This way, only "Ninja/Adult" will be left during registration.
Hence, this information will not be displayed during registration, but when joining a dojo, and in a different way ( very probably a popup with N cards, N being the possible "roles" (Ninja/Parent/Mentor/Champion) ), every bulletpoint will probably being reused there as a description per card.
That should let us with an easier codebase to maintain and easier to use for the users :)
Otherwise, I don't have the mockups right now to verify the order of the cards, but I would probably put parents before mentors; and kids shouldn't have this display to choose a role anymore as their role should be defined by their age ;p

**Comment by Wardormeur** [comment]
@DanielBrierton to close? We don't use those usertype on registration

**Comment by DanielBrierton** [comment]
@Wardormeur Sounds good to me!
